/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ButtonUpdate { 
    name?: string | null;
    macro?: string | null;
    style?: string | null;
    other?: string | null;
    css_class?: string | null;
    display?: boolean | null;
}

