/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ButtonPublic { 
    /**
     * Button name
     */
    name: string;
    /**
     * Script name
     */
    macro: string;
    style?: string | null;
    other?: string | null;
    css_class?: string | null;
    /**
     * Display button
     */
    display?: boolean;
    id: number;
}

