/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type } from './type';
import { Level } from './level';


export interface Config { 
    /**
     * Servo
     */
    servo?: boolean;
    /**
     * Pipan
     */
    pipan?: boolean;
    /**
     * Pi Light
     */
    pilight?: boolean;
    /**
     * Class
     */
    upreset?: Type;
    /**
     * Log level
     */
    loglevel?: Level;
}
export namespace Config {
}


