/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Files { 
    /**
     * File name
     */
    name: string;
    /**
     * I/T/V
     */
    type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Icon
     */
    icon: string;
    /**
     * DateTime
     */
    datetime: string;
    /**
     * Read/Write right on disk
     */
    locked?: boolean;
    realname: string;
    /**
     * Index
     */
    number: string;
    lapse_count?: number | null;
    duration?: number | null;
    id?: string | null;
}

