/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Rsync { 
    rs_enabled?: boolean;
    rs_user?: string | null;
    rs_pwd?: string | null;
    rs_direction?: string | null;
    rs_mode?: string;
    rs_remote_host?: string | null;
    rs_options?: Array<string>;
}

