/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DaysMode } from './daysMode';
import { Week } from './week';


export interface SchedulerUpdate { 
    id: number;
    command_on?: string | null;
    command_off?: string | null;
    mode?: string | null;
    enabled?: boolean | null;
    period?: string | null;
    daysmode_id?: number | null;
    daysmode: DaysMode;
    calendars: Week;
}

