/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUpdate { 
    enabled?: boolean | null;
    locale?: string | null;
    name?: string | null;
    password?: string | null;
    otp_confirmed?: boolean | null;
    right?: number | null;
}

