/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreate { 
    enabled?: boolean;
    locale?: string;
    name: string;
    otp_confirmed?: boolean;
    right: number;
    password: string;
}

