/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Level = 'INFO' | 'WARNING' | 'ERROR' | 'DEBUG';

export const Level = {
    Info: 'INFO' as Level,
    Warning: 'WARNING' as Level,
    Error: 'ERROR' as Level,
    Debug: 'DEBUG' as Level
};

