/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Locale = 'FR' | 'EN';

export const Locale = {
    Fr: 'FR' as Locale,
    En: 'EN' as Locale
};

