/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Level } from './level';


export interface Log { 
    datetime: string;
    level: Level;
    msg: string;
}
export namespace Log {
}


