/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Schedule { 
    autocamera_interval: number;
    autocapture_interval: number;
    cmd_poll: number;
    dawnstart_minutes: number;
    dayend_minutes: number;
    daymode: number;
    daystart_minutes: number;
    duskend_minutes: number;
    gmt_offset: string;
    latitude: number;
    longitude: number;
    management_command?: string | null;
    management_interval: number;
    max_capture: number;
    mode_poll: number;
    purgeimage_hours: number;
    purgelapse_hours: number;
    purgevideo_hours: number;
    purgespace_level: number;
    purgespace_modeex: number;
}

