/**
 * ViewPI Camera
 * Backend for RaspiMjpeg
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Type = 'v2' | 'N-IMX219' | 'P-IMX219' | 'N-OV5647' | 'P-OV5647';

export const Type = {
    V2: 'v2' as Type,
    NImx219: 'N-IMX219' as Type,
    PImx219: 'P-IMX219' as Type,
    NOv5647: 'N-OV5647' as Type,
    POv5647: 'P-OV5647' as Type
};

